/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NumberAdder;

import my.numberadder.NumberAdderUI;

public class App {
    public static void main(String[] args) {
  
        NumberAdderUI.main(args);
    }
}
